name: terragrunt

on:
  push:
    branches:
      - main

jobs:
  manual_run:
    # if: github.event_name == 'issue_comment' &&
    #       contains(github.event.comment.html_url, '/pull/') && 
    #       startsWith(github.event.comment.body, '/run')
    runs-on: ubuntu-latest

    steps:
      # - name: Get branch name and sha
      #   id: get_branch
      #   run: |
      #     PR=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.issue.pull_request.url }})
      #     echo "::set-output name=branch::$(echo $PR | jq -r '.head.ref')"
      #     echo "::set-output name=sha::$(echo $PR | jq -r '.head.sha')"

      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ steps.get_branch.outputs.branch }}

      - name: Install aqua
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.35.0
          aqua_opts: "-l"

      - name: Run
        run: |
          terragrunt --version
